{% set name = "psfgen" %}
{% set version = "1.0.5" %}
{% set sha256 = "a514be6af7b6ee2d09aca7a45917c0336834f64ae3b434b29ec61e9071673b5c" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/Eigenstate/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1
    skip: true  # [win]
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
    build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
    host:
        - python
        - pip
        - setuptools
    run:
        - python

test:
    imports:
        - pytest
        - psfgen
    requires:
        - pytest
        - vmd-python >=3.0.0
    commands:
        - py.test --pyargs psfgen

about:
    home: https://github.com/Eigenstate/psfgen
    license: VMD
    license_file: LICENSE
    summary: "Protein Structure builder, with Python bindings"
    description: |
        PSFGen is a structure building tool distributed with VMD
        used to prepare systems for simulation with the CHARMM
        forcefield.
    doc_url: https://psfgen.robinbetz.com
    dev_url: https://github.com/Eigenstate/psfgen

extra:
    recipe-maintainers:
        - Eigenstate
